spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taller360_simplificado
    username: root
    password: mitzi
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
      show-sql: true
    properties:
      hibernate:
        format-sql: true
server:
  port : 8083
logging:
 level:
   org:

     springframework: INFO
     apache: ERROR
     mongodb: INFO

     hibernate:

       Version: ERROR
       stat: ERROR
       SQL: DEBUG
       cache: ERROR
       tool: ERROR

   com:
     eoi: INFO
     zaxxer: INFO
   root: INFO
 server:
   error:
     whitelabel:
       enabled = true